### ISSUE TITLE
Plex 7.0 (next)

### ISSUE THREAD

**Issue by vpicone** [IBM/plex#370]
## Goals
- Able to include any Plex language for internationalization
- Able to include any additional font weights for a font family
- Able to include any additional font style variants for a font family
- Migrate to Dart Sass

## Requirements
- There is a sensible fallback that uses a CDN by default
- Able to self-host font files

## To-do
- [x] Update Hebrew and Arabic to use latest PostScript/Font names
- [x] Add tooling for easier/automated pre-release and release procedures
- [x] Utilize Sass modules to permit modular builds based on application requirements (weights, languages, font-face features) for Carbon languages +1 non-standard variant
- [x] Remove ie11 font files (eot/ttf/otf)
- [ ] Add semver to font files
- [ ] Same as above but for all languages
- [ ] Use [@forward](https://sass-lang.com/documentation/at-rules/forward) rule
- [ ] Add support for subsets
- [ ] Create declarations for Variable font
- [ ] Document build pipeline and release procedures
- [ ] Fix Korean asset zip for github release
- [x] Add IBM Plex Sans JP to github for release
- [x] Add IBM Plex JP sample text to IDL typetester —> “Non-Latin scripts” https://github.com/carbon-design-system/design-language-website/issues/965

**Comment by johnnyshields** [comment]
Is Japanese included in this release?

**Comment by vpicone** [comment]
@johnnyshields It's not, @BoldMonday do we have an update on the intended release date for Japanese?

**Comment by mjabbink** [comment]
@johnnyshields Our current estimate is sometime in June. The latter part of the month to be safe.

**Comment by johnnyshields** [comment]
@mjabbink thanks, we're looking forward to it at TableCheck

**Comment by rekollekt** [comment]
>     * Able to include any additional font weights for a font family
@vpicone It means that will be 9 weights (from 100 to 900) plus italics (18 styles)?

**Comment by EatonZ** [comment]
It appears that the "split" fonts are included as font files in the latest `next`, but they aren't declared in the CSS/SCSS. Is this because it's not done or are split fonts being phased out for 6.0?

**Comment by elyran2** [comment]
when will Hebrew be fixed? it's been almost a year since I reported kerning issues in Hebrew and someone said that it is already fixed but no new version is published... why wait on it?

**Comment by vpicone** [comment]
@johnnyshields Correction, it looks like we'll be able to include IBM Plex Sans JP in this release.

**Comment by mjabbink** [comment]
@elyran2 The Hebrew fixes will be resolved in the next release. @vpicone can provide a more accurate timeline. 
There are many updates but a few in Arabic and Hebrew are at the top of the list.

**Comment by kifzuka** [comment]
Add font ligature please, it's very nice to code with

**Comment by mjabbink** [comment]
@kifzuka
<img width="765" alt="Screen Shot 2021-06-29 at 1 11 44 PM" src="https://user-images.githubusercontent.com/32881239/123846951-99850080-d8db-11eb-9218-e686eb4d6297.png">

<img width="769" alt="Screen Shot 2021-06-29 at 1 11 17 PM" src="https://user-images.githubusercontent.com/32881239/123846977-9f7ae180-d8db-11eb-8d78-74e1f2834da0.png">

**Comment by BoldMonday** [comment]
> Add font ligature please, it's very nice to code with

Coding ligatures have been discussed in https://github.com/IBM/plex/issues/63

**Comment by kifzuka** [comment]
> @kifzuka
> <img alt="Screen Shot 2021-06-29 at 1 11 44 PM" width="765" src="https://user-images.githubusercontent.com/32881239/123846951-99850080-d8db-11eb-9218-e686eb4d6297.png">
> 
> <img alt="Screen Shot 2021-06-29 at 1 13 23 PM" width="763" src="https://user-images.githubusercontent.com/32881239/123847127-ce915300-d8db-11eb-9363-9e387f318dbb.png">

Ligatures for coding, programming like 'Fira code'

**Comment by vpicone** [comment]
@mjabbink @katie-A-IBM my plan is to have the Japanese files released in a beta by Friday with an official release by the end of next week.

I'll update the video and remove the Noto card ASAP.

**Comment by mjabbink** [comment]
Thanks for update @vpicone I already removed the Noto Card https://github.com/carbon-design-system/design-language-website/pull/972

The only think left is to add the Plex JP in the type tester section with sample text and placement all provided here https://github.com/carbon-design-system/design-language-website/issues/965

**Comment by EatonZ** [comment]
Hi - any comment on [my question above](https://github.com/IBM/plex/issues/370#issuecomment-858305261) yet?

**Comment by vpicone** [comment]
> Hi - any comment on [my question above](https://github.com/IBM/plex/issues/370#issuecomment-858305261) yet?

Yes, the styles will use subsets. You can see subsets in the list of items at the top of the issue.

**Comment by EatonZ** [comment]
@vpicone Thanks, didn't know those were called "subsets".

**Comment by mjabbink** [comment]
@vpicone Let’s add the Plex Mono update to GitHub.

**Comment by BoldMonday** [comment]
@mjabbink @vpicone And Plex Sans Hebrew + Plex Sans Arabic updates please.

**Comment by mjabbink** [comment]
Those are not released either! Oh wow. OK, we gotta get that done. 

@alisonjoseph We defiantly need to get these in this sprint.

**Comment by vpicone** [comment]
@mjabbink Hebrew and Arabic are released under the next branch: https://github.com/IBM/plex/releases/tag/v6.0.0-next.6

**Comment by mjabbink** [comment]
@vpicone status on this?

**Comment by subnut** [comment]
Implement #401 please. I find markdown's headings like `#####` _very_ hard to read due to the separation in between.

**Comment by mjabbink** [comment]
@vpicone Any updates for this issue?

**Comment by barmadrid** [comment]
Would love to hear the progress on this!

**Comment by Hackgets** [comment]
I am not a programmer, so I am waiting for a Japanese monospace font that is suitable for general use and still highly legible. That's why I have high hopes for IBM Plex.

In open source projects, it is unavoidable that Japanese language support is lacking. This is because there are few Japanese contributors, and I am ashamed of that.

**Comment by Yoshiko321** [comment]
We are observing an issue where non-breaking space  (&amp;nbsp;) becomes visible as ” □ ” when accessing from iPhone iOS 15.4 browser. This is for IBM Plex Sans JP font.
<img width="469" alt="image" src="https://user-images.githubusercontent.com/105399870/167969495-9c66e59f-ec73-4edf-b39f-525b58584a48.png">

- This is not the case for iOS 15.3
- This phenomena is not observed on US page for non-breaking space

Might you be able to help? @BoldMonday

**Comment by BoldMonday** [comment]
@Yoshiko321 I suspect this is a text encoding problem in 15.4 instead of a font problem. I'm afraid we're unable to help here.

**Comment by XenBG** [comment]
@vpicone

The Bulgarian Minister of e-Government Bozhidar Bojanov has launched an initiative for Bulgarian institutions to use fonts that support Bulgarian Cyrillic. Source: https://www.facebook.com/bozhidar.bozhanov/posts/pfbid036YFX1SuEjFv4Mzg4WGfdnmCSG6yKT5f4wBokqjZigxCER6tkFdmrxzsD6xeedLBzl

The Roboto font is widely used in the Bulgarian web and I suggest you add support for the Bulgarian Cyrillic Script so that everyone can take advantage of it. You can read more about the loclBGR glyphs with examples and info on this article - https://www.lettersoup.de/what-shall-be-done-for-bulgarian-cyrillic-loclbgr/

I will be more than grateful if you consider my proposal!

![bg-ru-cyrillic](https://user-images.githubusercontent.com/4932709/171821605-723566cf-c9a8-49c2-8362-7b0683fcadc1.png)

**Comment by Skr-ZERO** [comment]
Seems like version 7.0 still doesn’t support Chinese… How many Chinese characters will be included in IBM Plex Sans SC & TC and when will they come out?

**Comment by mjabbink** [comment]
@Skr-ZERO Plex Sans SC & TC will be released in 2023. Roughly 30,000 glyphs.

**Comment by jerviscui** [comment]
Very much looking forward to supporting Chinese.

**Comment by Marcus98T** [comment]
Is there any reason why Plex Sans TC and SC got delayed yet again to 2024? The Plex website still says 2023.

I don't want to speculate, but manually drawing new Chinese glyphs and extensive quality checks may be one of the reasons?

**Comment by cssobral2013** [comment]
Are Greek/Cyrillic support for Variable planned?
